samples = ['CDS001D', 'CDS002D', 'CDS004D', 'CDS005D', 'CDS007D', 'CDS008D','CDS010D', 'CDS011D', 'CDS013D', 'CDS014D', 'CDS016D', 'CDS017D']

chro_list=['2L', '2R', '3L', '3R', '4','X']


path_to_juicer_tool='/mnt/e/juicer_tools/juicer_tools.jar'

rule all:
    input:
        expand("../data/cool_10k/{sample}_10000.cool", sample=samples),
        expand("../data/cool_10k_targetChroms/{sample}_10000_targetChroms.cool", sample=samples),
        expand("../data/cool_10k_targetChroms_normalizeSmallest/{sample}_10000_targetChroms_normalizeSmallest.cool", sample=samples),
        expand("../results/results_hicRep_calculate_scc_pairwise/output_scc_{sample1}_vs_{sample2}.txt", sample1=samples, sample2=samples)

rule hic_to_cool:
    input:
        "../data/hic/{sample}.hic"
    output:
        "../data/cool_10k/{sample}_10000.cool"
    params:
        output_name="../data/cool_10k/{sample}.cool"
    shell:
        "hicConvertFormat -m {input} --inputFormat hic --outputFormat cool -o {params.output_name} -r 10000"

rule take_targetChroms:
    input:
        "../data/cool_10k/{sample}_10000.cool"
    output:
        "../data/cool_10k_targetChroms/{sample}_10000_targetChroms.cool"
    shell:
        " hicAdjustMatrix -m {input} --action keep --chromosomes 2L 2R 3L 3R 4 X -o {output}"


rule normalize_smallest:
    input:
        cool_files=expand("../data/cool_10k_targetChroms/{sample}_10000_targetChroms.cool", sample=samples)
    output:
        cool_normalized=expand("../data/cool_10k_targetChroms_normalizeSmallest/{sample}_10000_targetChroms_normalizeSmallest.cool", sample=samples)
    shell:
        "hicNormalize -m {input.cool_files} --normalize smallest -o {output.cool_normalized}"



rule hicRep_calculate_scc:
    input:
        sample1="../data/cool_10k_targetChroms_normalizeSmallest/{sample1}_10000_targetChroms_normalizeSmallest.cool",
        sample2="../data/cool_10k_targetChroms_normalizeSmallest/{sample2}_10000_targetChroms_normalizeSmallest.cool"
    output:
        "../results/results_hicRep_calculate_scc_pairwise/output_scc_{sample1}_vs_{sample2}.txt"
    shell:
        """
        hicrep {input.sample1} {input.sample2} {output} --h 20 --dBPMax 500000
        """



