# samples = ['CDS001D_combined', 'CDS002D_combined', 'CDS004D_combined', 'CDS005D_combined', 'HS_combined_PNAS.pairs_dn10000000', 'HS_me3_ac_combined','WT_combined_PNAS.pairs_dn10000000', 'WT_me3_ac_combined']
samples = ['CDS001D_combined', 'CDS004D_combined', 'WT_combined_PNAS.pairs_dn10000000', 'WT_me3_ac_combined']
chro_list=['2L', '2R', '3L', '3R', '4','X']



rule all:
    input:
        expand("../data/cool_10k/{sample}_10000.cool", sample=samples),
#         expand("../data/cool_10k_targetChroms/{sample}_10000_targetChroms.cool", sample=samples),
#         expand("../data/cool_10k_targetChroms_normalize_0_1/{sample}_10000_targetChroms_normalize_0_1.cool", sample=samples),
        expand("../results/results_hicRep_calculate_scc_pairwise/output_scc_{sample1}_vs_{sample2}.txt", sample1=samples, sample2=samples)

# rule hic_to_cool:
#     input:
#         "../data/hic/{sample}.hic"
#     output:
#         "../data/cool_10k/{sample}_10000.cool"
#     params:
#         output_name="../data/cool_10k/{sample}.cool"
#     shell:
#         "hicConvertFormat -m {input} --inputFormat hic --outputFormat cool -o {params.output_name} -r 10000"
# #
# rule take_targetChroms:
#     input:
#         "../data/cool_10k/{sample}_10000.cool"
#     output:
#         "../data/cool_10k_targetChroms/{sample}_10000_targetChroms.cool"
#     shell:
#         " hicAdjustMatrix -m {input} --action keep --chromosomes 2L 2R 3L 3R 4 X -o {output}"
# #
# #
# rule normalize_0_1:
#     input:
#         cool_files=expand("../data/cool_10k_targetChroms/{sample}_10000_targetChroms.cool", sample=samples)
#     output:
#         cool_normalized=expand("../data/cool_10k_targetChroms_normalize_0_1/{sample}_10000_targetChroms_normalize_0_1.cool", sample=samples)
#     shell:
#         "hicNormalize -m {input.cool_files} --normalize norm_range -o {output.cool_normalized}"



rule hicRep_calculate_scc:
    input:
        sample1="../data/cool_10k_targetChroms_normalize_0_1/{sample1}_10000_targetChroms_normalize_0_1.cool",
        sample2="../data/cool_10k_targetChroms_normalize_0_1/{sample2}_10000_targetChroms_normalize_0_1.cool"
    output:
        "../results/results_hicRep_calculate_scc_pairwise/output_scc_{sample1}_vs_{sample2}.txt"
    shell:
        """
        hicrep {input.sample1} {input.sample2} {output} --h 20 --dBPMax 500000
        """



